version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: hummingbird 
      MYSQL_USER: hummingbird
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - brnet1

  hummingbird:
    depends_on:
      - db
    image: php:7.4.33-apache
    volumes:
      - ./:/var/www/hummingbird:cached
    ports:
      - 8081:8081
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/hummingbird/web
    networks:
      - brnet1
    restart: unless-stopped
    command: sh -c "/var/www/hummingbird/yii migrate --migrationPath=@yii/rbac/migrations && /var/www/hummingbird/yii migrate --migrationPath=@mdm/admin/migrations && /var/www/hummingbird/yii migrate/up"

volumes:
  db:

networks:
  brnet1: