version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: hummingbird 
      MYSQL_USER: hummingbird
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - brnet1

  hummingbird:
    build: .
    container_name: hummingbird
    volumes:
      - ./:/var/www/hummingbird:cached
    ports:
      - 8081:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/hummingbird/web
    networks:
      - brnet1
    restart: unless-stopped
    command: /bin/sh -c "/var/www/hummingbird/docker-entrypoint.sh && apache2-foreground"
    depends_on:
      - db

volumes:
  dbdata:

networks:
  brnet1: