<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Database' => '添加数据库',
    'Create Report' => '创建报表',
    'Database Management' => '数据库管理',
    'Databases can be query' => '可供查询的数据库',
    'Enter your username and password to login:' => '输入用户名和密码登录：',
    'Export' => '导出',
    'Favorite Management' => '收藏夹管理',
    'Forget password' => '忘记密码',
    'Formatted SQL' => '查询格式化',
    'Login' => '登录',
    'Manage your favorite list' => '管理的收藏列表',
    'Not registerd? Sign up now.' => '还没注册？点此注册',
    'Query' => '查询',
    'Query Result' => '查询结果',
    'Role based authorization control' => '基于角色的访问控制',
    'Save Report' => '保存报表',
    'System Management' => '系统管理',
    'User Management' => '用户管理',
    'Username' => '用户名',
    'Welcome to Hummingbird reporting system!' => '欢迎使用 Hummingbird 微报表系统！',
    'Add or remove users' => '添加或者删除用户',
    'Authorization' => '授权管理',
    'Congratulations!' => '恭喜你',
    'Connection Charset' => '连接字符集',
    'Created Time' => '创建时间',
    'Database Alias' => '别名',
    'Database Name' => '数据库名',
    'Host' => '主机',
    'Last Updated Time' => '最后更新时间',
    'Password' => '密码',
    'User Name' => '用户名',
];
