<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add or remove users' => '',
    'Authorization' => '',
    'Congratulations!' => '',
    'Create Database' => '',
    'Create Report' => '',
    'Database Management' => '',
    'Databases can be query' => '',
    'Enter your username and password to login:' => '',
    'Export' => '',
    'Favorite Management' => '',
    'Forget password' => '',
    'Formatted SQL' => '',
    'Login' => '',
    'Manage your favorite list' => '',
    'Not registerd? Sign up now.' => '',
    'Query' => '',
    'Query Result' => '',
    'Role based authorization control' => '',
    'Save Report' => '',
    'System Management' => '',
    'User Management' => '',
    'Username' => '',
    'Welcome to Hummingbird reporting system!' => '',
    'Connection Charset' => '连接字符集',
    'Created Time' => '创建时间',
    'Database Alias' => '别名',
    'Database Name' => '数据库名',
    'Host' => '主机',
    'Last Updated Time' => '最后更新时间',
    'Password' => '密码',
    'User Name' => '用户名',
];
